In [1]:
#!pip install tensorflow
#!pip install pandas as pd
#!pip install numpy as np
#!pip install --upgrade pip

In [2]:
import pandas as pd
import numpy as np

In [3]:
from keras.datasets import mnist

In [4]:
df = pd.read_csv("hero_selection_final.csv")

In [5]:
matrix1 =np.array(df.loc[:,['match_id', 'Result','index_h1','index_h2','index_h3','index_h4', 'index_h5']])
matrix1

array([[1928898739, 1, '1/28', ..., '3/11', '4/75', '5/94'],
       [1928932285, 1, '1/74', ..., '3/5', '4/70', '5/62'],
       [1928918721, -1, '1/42', ..., '3/32', '4/97', '5/104'],
       ...,
       [1829200497, -1, '1/112', ..., '3/69', '4/39', '5/57'],
       [1829177389, 1, '1/30', ..., '3/6', '4/2', '5/48'],
       [1829220503, -1, '1/29', ..., '3/25', '4/6', '5/72']], dtype=object)

In [6]:
df1 = pd.read_csv("hero_names.csv")

In [7]:
matrix2 =np.array(df1.loc[:,['hero_id', 'Strength','Agility','Intelligence']])

In [8]:
len(matrix2)

113

In [9]:
df2 = pd.read_csv("hero_selection.csv")

match_id  Radiant_win  Result  Hero1  Hero2  Hero3  Hero4  Hero5  \
0       1928898739         True       1     28     29     11     75     94   
1       1928932285         True       1     74     35      5     70     62   
2       1928918721        False      -1     42     26     32     97    104   
3       1928896797         True       1     30     70     26     81     36   
4       1928893986         True       1     26      4     37     34     32   
...            ...          ...     ...    ...    ...    ...    ...    ...   
233730  1829201186         True       1     30     70     95     21    104   
233731  1829146665         True       1     26     29     70     72      1   
233732  1829200497        False      -1    112     44     69     39     57   
233733  1829177389         True       1     30     20      6      2     48   
233734  1829220503        False      -1     29     30     25      6     72   

                  target  
0        28/29/11/75/94/  
1         74/35/5/70/62/  
2       42/26/32/97/104/  
3        30/70/26/81/36/  
4         26/4/37/34/32/  
...                  ...  
233730  30/70/95/21/104/  
233731    26/29/70/72/1/  
233732  112/44/69/39/57/  
233733     30/20/6/2/48/  
233734    29/30/25/6/72/  

[233735 rows x 9 columns]

In [129]:
matrix3 =np.array(df2.loc[:,['target']])

In [141]:
'''Category prediction of hero5 will contain the data of hero1, hero2, hero3, hero4.'''
matrix4 =np.array(df2.loc[:,[ 'Hero1','Hero2','Hero3','Hero4']])
matrix5 = np.array(df2.loc[:,[ 'Hero5']])
'''Category prediction of hero2 will contain the data of hero1.'''
matrix43 =np.array(df2.loc[:,[ 'Hero1']])
matrix53 = np.array(df2.loc[:,[ 'Hero2']])
'''Category prediction of hero3 will contain the data of hero1, hero2.'''
matrix42 =np.array(df2.loc[:,[ 'Hero1','Hero2']])
matrix52 = np.array(df2.loc[:,[ 'Hero3']])
'''Category prediction of hero4 will contain the data of hero1, hero2, hero3'''
matrix41 =np.array(df2.loc[:,[ 'Hero1','Hero2','Hero3']])
matrix51 = np.array(df2.loc[:,[ 'Hero4']])
matrix5.shape

(233735, 1)

In [158]:
''' target variable contains the category of next hero picked in the next pick. '''
def test_train(matrix4, matrix5):
    feature_matrixes = matrix4
    target_features = matrix5
    train_data = feature_matrixes[0:40000]
    test_data = feature_matrixes[40000:50000]
    train_target = target_features[0:40000]
    test_target = target_features[40000:50000]
    
    #train target preparation for categorical data
    train_target.reshape(40000,)
    final_index=[]
    for i in range(40000):
        hero = int(train_target[i][0])
        indexed = matrix2[hero-1]
      
        if indexed[1]==1:
            final_index.append(1)
        elif indexed[2]==1:
            final_index.append(2)
        elif indexed[3]==1:
            final_index.append(3)
    final_index = np.array(final_index)
    
    #test target preparation for categorical data
    test_target.reshape(10000,)
    final_index_test=[]
    for i in range(10000):
        hero = int(test_target[i][0])
        indexed = matrix2[hero-1]  
        if indexed[1]==1:
            final_index_test.append(1)
        elif indexed[2]==1:
            final_index_test.append(2)
        elif indexed[3]==1:
            final_index_test.append(3)
    final_index_test = np.array(final_index_test)
    
    return train_data, final_index, test_data, final_index_test

In [159]:
train_data5, final_index5, test_data5, final_index_test5 = test_train(matrix4[0:50000], matrix5[0:50000])
train_data4, final_index4, test_data4, final_index_test4 = test_train(matrix41[0:50000], matrix51[0:50000])
train_data3, final_index3, test_data3, final_index_test3 = test_train(matrix42[0:50000], matrix52[0:50000])
train_data2, final_index2, test_data2, final_index_test2 = test_train(matrix43[0:50000], matrix53[0:50000])
#train_data.shape

In [160]:
import tensorflow as tf
#import keras
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical

In [161]:
'''Started the neural networks implementation with a basic neural networks model. 2 dense layers of relu.
   Activation method relu is used because relu is computationaly effective and it converges soon. Last layer has 
   activation method softmax because our problem set is a multi class problem.
'''
# Build the model.

model = Sequential([
  Dense(40, activation='relu'),
  Dense(30, activation='relu'),
  Dense(4, activation='softmax'),
])

model1 = Sequential([
  Dense(40, activation='relu'),
  Dense(30, activation='relu'),
  Dense(4, activation='softmax'),
])

model2 = Sequential([
  Dense(40, activation='relu'),
  Dense(30, activation='relu'),
  Dense(4, activation='softmax'),
])

model3 = Sequential([
  Dense(40, activation='relu'),
  Dense(30, activation='relu'),
  Dense(4, activation='softmax'),
])

In [162]:
'''for compilation of the model for every hero I have used adam optimizer because this updates network weights 
   iteratively based on the training data.
   Categorical crossentropy loss function is used when there are two or more label classes.
'''


# Compile the model.
model.compile("adam", "categorical_crossentropy", metrics=["accuracy"])
model1.compile("adam", "categorical_crossentropy", metrics=["accuracy"])
model2.compile("adam", "categorical_crossentropy", metrics=["accuracy"])
model3.compile("adam", "categorical_crossentropy", metrics=["accuracy"])

In [163]:
model.fit(
  train_data5,
  to_categorical(final_index5),
  epochs=20,
  batch_size=32
)

model1.fit(
  train_data4,
  to_categorical(final_index4),
  epochs=20,
  batch_size=32
)

model2.fit(
  train_data3,
  to_categorical(final_index3),
  epochs=20,
  batch_size=32
)

model3.fit(
  train_data2,
  to_categorical(final_index2),
  epochs=20,
  batch_size=32
)

Epoch 1/20
1250/1250 [==============================] - 1s 528us/step - loss: 1.3742 - accuracy: 0.3521
Epoch 2/20
1250/1250 [==============================] - 1s 501us/step - loss: 1.1832 - accuracy: 0.3598
Epoch 3/20
1250/1250 [==============================] - 1s 520us/step - loss: 1.1578 - accuracy: 0.3607
Epoch 4/20
1250/1250 [==============================] - 1s 549us/step - loss: 1.1432 - accuracy: 0.3619
Epoch 5/20
1250/1250 [==============================] - 1s 566us/step - loss: 1.1338 - accuracy: 0.3679
Epoch 6/20
1250/1250 [==============================] - 1s 537us/step - loss: 1.1193 - accuracy: 0.3696
Epoch 7/20
1250/1250 [==============================] - 1s 525us/step - loss: 1.1129 - accuracy: 0.3734
Epoch 8/20
1250/1250 [==============================] - 1s 531us/step - loss: 1.1044 - accuracy: 0.3799
Epoch 9/20
1250/1250 [==============================] - 1s 535us/step - loss: 1.1002 - accuracy: 0.3839
Epoch 10/20
1250/1250 [==============================] - 1s 552u

1250/1250 [==============================] - 1s 534us/step - loss: 0.9775 - accuracy: 0.5393
Epoch 20/20
1250/1250 [==============================] - 1s 505us/step - loss: 0.9775 - accuracy: 0.5393


In [164]:
model.evaluate(
  test_data5,
  to_categorical(final_index_test5)
)

model1.evaluate(
  test_data4,
  to_categorical(final_index_test4)
)

model2.evaluate(
  test_data3,
  to_categorical(final_index_test3)
)

model3.evaluate(
  test_data2,
  to_categorical(final_index_test2)
)

313/313 [==============================] - 0s 409us/step - loss: 0.9849 - accuracy: 0.5369


[0.9848888516426086, 0.536899983882904]

In [165]:
predictions5 = model.predict(test_data5)
predictions4 = model1.predict(test_data4)
predictions3 = model2.predict(test_data3)
predictions2 = model3.predict(test_data2)
print(predictions)

[[5.0646087e-10 2.9393274e-01 4.0024436e-01 3.0582294e-01]
 [1.1529791e-15 2.8407830e-01 4.3090093e-01 2.8502074e-01]
 [7.5483239e-12 3.0070078e-01 4.2877913e-01 2.7052009e-01]
 ...
 [4.3918187e-13 2.4348556e-01 2.9443315e-01 4.6208134e-01]
 [2.0445063e-09 3.1696898e-01 3.7978116e-01 3.0324987e-01]
 [3.5292400e-09 3.1025571e-01 4.0674189e-01 2.8300241e-01]]


In [166]:
print(np.argmax(predictions5, axis=1)) # [7, 2, 1, 0, 4]
y_pred5 = np.argmax(predictions, axis=1)
y_pred4 = np.argmax(predictions4, axis=1)
y_pred3 = np.argmax(predictions3, axis=1)
y_pred2 = np.argmax(predictions2, axis=1)

[2 2 2 ... 2 2 2]


In [167]:
'''Self test is used. final_index_test5 contains the test target for 5th hero.
    Similarly, final_index_test4 is for 4th hero, final_index_test3 is for 3rd hero, 
    final_index_test4 is for 2nd hero.
'''
my_ytest5 = np.array(final_index_test5)
my_ytest4 = np.array(final_index_test4)
my_ytest3 = np.array(final_index_test3)
my_ytest2 = np.array(final_index_test2)

my_ytest_finalhero5 = my_ytest5
my_ytest_finalhero4 = my_ytest4
my_ytest_finalhero3 = my_ytest3
my_ytest_finalhero2 = my_ytest2

#my_ytest_finalhero
my_ypred5 = np.array(y_pred5)
my_ypred4 = np.array(y_pred4)
my_ypred3 = np.array(y_pred3)
my_ypred2 = np.array(y_pred2)

my_ypred_finalhero5 = my_ypred5
my_ypred_finalhero4 = my_ypred4
my_ypred_finalhero3 = my_ypred3
my_ypred_finalhero2 = my_ypred2

#my_ypred_finalhero
totals = my_ytest5.shape[0]
#totals
num_correct5 = sum(p == t for p, t in zip(my_ypred_finalhero5, my_ytest_finalhero5))
num_correct4 = sum(p == t for p, t in zip(my_ypred_finalhero4, my_ytest_finalhero4))
num_correct3 = sum(p == t for p, t in zip(my_ypred_finalhero3, my_ytest_finalhero3))
num_correct2 = sum(p == t for p, t in zip(my_ypred_finalhero2, my_ytest_finalhero2))

#num_correct
total5 = (num_correct5/totals)*100
total4 = (num_correct4/totals)*100
total3 = (num_correct3/totals)*100
total2 = (num_correct2/totals)*100

print("Prediction accuracy for 5th hero:", total5)
print("Prediction accuracy for 4th hero:", total4)
print("Prediction accuracy for 3rd hero:", total3)
print("Prediction accuracy for 2nd hero:", total2)

Prediction accuracy for 5th hero: 19.52
Prediction accuracy for 4th hero: 36.28
Prediction accuracy for 3rd hero: 40.21
Prediction accuracy for 2nd hero: 53.690000000000005
