In [85]:
import pandas as pd

In [86]:
import numpy as np


In [113]:
df = pd.read_csv("hero_selection_final.csv")

In [114]:
df.head()
#df['new_col'] = list(zip(df.lat, df.long))

match_id  Result index_h1 index_h2 index_h3 index_h4 index_h5  \
0  1928898739       1     1/28     2/29     3/11     4/75     5/94   
1  1928932285       1     1/74     2/35      3/5     4/70     5/62   
2  1928918721      -1     1/42     2/26     3/32     4/97    5/104   
3  1928896797       1     1/30     2/70     3/26     4/81     5/36   
4  1928893986       1     1/26      2/4     3/37     4/34     5/32   

   Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  Unnamed: 11  Unnamed: 12  \
0         NaN         NaN         NaN          NaN          NaN          NaN   
1         NaN         NaN         NaN          NaN          NaN          NaN   
2         NaN         NaN         NaN          NaN          NaN          NaN   
3         NaN         NaN         NaN          NaN          NaN          NaN   
4         NaN         NaN         NaN          NaN          NaN          NaN   

   Unnamed: 13  Unnamed: 14  Unnamed: 15  Unnamed: 16  Unnamed: 17  \
0          NaN          NaN          NaN          NaN          NaN   
1          NaN          NaN          NaN          NaN          NaN   
2          NaN          NaN          NaN          NaN          NaN   
3          NaN          NaN          NaN          NaN          NaN   
4          NaN          NaN          NaN          NaN          NaN   

   Unnamed: 18  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

In [252]:
#print(df['index_h1'])
matrix1 =np.array(df.loc[:,['match_id', 'Result','index_h1','index_h2','index_h3','index_h4', 'index_h5']])
matrix1

array([[1928898739, 1, '1/28', ..., '3/11', '4/75', '5/94'],
       [1928932285, 1, '1/74', ..., '3/5', '4/70', '5/62'],
       [1928918721, -1, '1/42', ..., '3/32', '4/97', '5/104'],
       ...,
       [1829200497, -1, '1/112', ..., '3/69', '4/39', '5/57'],
       [1829177389, 1, '1/30', ..., '3/6', '4/2', '5/48'],
       [1829220503, -1, '1/29', ..., '3/25', '4/6', '5/72']], dtype=object)

In [220]:
df1 = pd.read_csv("hero_names.csv")

In [292]:
matrix2 =np.array(df1.loc[:,['hero_id', 'Strength','Agility','Intelligence']])

In [222]:
len(matrix2)

113

In [223]:
matrix2[112]

array([113,   0,   1,   0])

In [241]:
import datetime

print(datetime_old)

print(datetime_new)


2020-11-17 12:14:21.475946
2020-11-17 12:14:21.476283
0:00:00.000337


In [242]:
m = 1
n = 2
o = 3
def features(match, hero_info):
    """Set of four features from lecture"""
    index = [1, 2, 3, 4, 5]
    hero_list = []
    #print(match)
    #print(hero_info)
    #def process_token(token):
    for token_num in range(2,7):
        token = str(match[token_num])
        #print("token", hero_info[int(token[2:])])
        #print(token[2:])
        hero_list.append(hero_info[int(token[2:])-1])
    hero_list = np.array(hero_list)
    f1 = 1 if hero_list[0][3]==1 and hero_list[1][3]==1 else 0
    f2 = 1 if hero_list[2][1]==1 else 0
    f3 = 1 if (hero_list[0][3]==1 and hero_list[1][1]==1) or (hero_list[1][3]==1 and hero_list[0][1]==1) else 0
    f4 = 1 if hero_list[1][3]==1 else 0
    f5 = 1 if hero_list[0][3]==1 else 0
    f6 = 1 if hero_list[0][1]==1 else 0
    f7 = 1 if hero_list[1][1]==1 else 0
    f8 = 1 if hero_list[3][2]==1 else 0
    f9 = 1 if hero_list[4][2]==1 or hero_list[4][3]==1 else 0
    f10 = 1
    return np.array([f1,f2,f3, f4, f5, f6, f7, f8, f9, f10])    

feature_matrix = [[0,0,0,0,0,0,0,0,0,0]]
datetime_old = datetime.datetime.now()
for i in range(len(matrix1)):
    a = np.array(feature_matrix)
    b = np.array([features(matrix1[i], matrix2)])
    #print(a)
    #print(b)
    feature_matrix = np.concatenate((a,b), axis=0)
feature_matrix = feature_matrix[1:]
datetime_new = datetime.datetime.now()
#print(feature_matrix)
print(feature_matrix.shape)
print(datetime_new - datetime_old)
    #np.concatenate([[np.append([feature_matrix], [features(matrix1[i], matrix2)]), axis=0)
    #feature_matrix = [np.append(feature_matrix, features(matrix1[i], matrix2), axis=0)]
#feature_matrix = np.array(feature_matrix)
#feature_matrix


#a = np.array([fe])
#b = np.array([[5, 6]])
#np.concatenate((a, b), axis=0)
#array([[1, 2],
       #[3, 4],
       #[5, 6]])
    #feature_matrix =  np.array(feature_matrix.append(features(matrix1[i], matrix2)))
#features(matrix1[112], matrix2)

(233735, 10)
0:17:37.573130


In [243]:
feature_matrix.shape

(233735, 10)

In [246]:
feature_matrix[20000:20010]

array([[1, 1, 0, 1, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 0, 1, 0, 0, 1],
       [0, 0, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 1, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 1, 0, 0, 0, 1],
       [1, 1, 0, 1, 1, 0, 0, 0, 1, 1]])

In [247]:
w = np.ones(10)
dot_product = np.matmul(feature_matrix, w)

In [249]:
dot_product.shape

(233735,)

In [250]:
np.exp(dot_product)

array([ 54.59815003,  54.59815003,  54.59815003, ...,  54.59815003,
       148.4131591 , 403.42879349])

In [251]:
dot_product

array([4., 4., 4., ..., 4., 5., 6.])

In [253]:
#def tagged_data():
matrix1

array([[1928898739, 1, '1/28', ..., '3/11', '4/75', '5/94'],
       [1928932285, 1, '1/74', ..., '3/5', '4/70', '5/62'],
       [1928918721, -1, '1/42', ..., '3/32', '4/97', '5/104'],
       ...,
       [1829200497, -1, '1/112', ..., '3/69', '4/39', '5/57'],
       [1829177389, 1, '1/30', ..., '3/6', '4/2', '5/48'],
       [1829220503, -1, '1/29', ..., '3/25', '4/6', '5/72']], dtype=object)

In [341]:
matrix2[61]
#matrix1[1]

array([62,  0,  1,  0])

In [393]:
def tagging(match, hero_matrix):
    final_list=[]
    middle_value=""
    for element in match:
    #print(element)
        middle_tag = ""
        hero_entry = 0
        index_value = 0
        element = str(element)
        length = len(element)
        #temp_list = []
        
        if(length>=3 and length<=5):
            temp_list = hero_matrix[int(element[2:])-1]
            if temp_list[1]==1:
                middle_tag = "St"
            elif temp_list[2]==1:
                middle_tag = "Ag"
            elif temp_list[3]==1:
                middle_tag = "It"
            index_value = match[1]
            hero_entry = element[2:]
            middle_value +=  middle_tag + "/"
            final_list.append((hero_entry, middle_value, index_value))
             
    return final_list

dataset = []
for i in range(len(matrix1)):
    dataset.append(tagging(matrix1[i], matrix2))
len(dataset)
#train_sent = dataset[0:200000]
train_sent = dataset[0:200000]
test_sent = dataset[200000:233735]
#test_sent = dataset[200000:233735]
dataset
    #hero_info[int(token[2:])-1]

[('28', 'St/', 1),
 ('29', 'St/St/', 1),
 ('11', 'St/St/Ag/', 1),
 ('75', 'St/St/Ag/It/', 1),
 ('94', 'St/St/Ag/It/Ag/', 1)]

In [381]:
def word2features(sent, i):
    word = sent[i][0]
    postag = sent[i][1]
    #print("feature",word, postag, i)
    #print(postag[0:2])
    features = {
        'bias': 1.0,
        'first_2_heros': (i==1 and postag[0:2]=='It' and postag[3:5]=='It'),
        'third_hero': (i==2 and postag[6:8]=='St'),
        'alternate_condition': (i==1 and ((postag[0:2]=='It' and postag[3:5]=='St')or(postag[0:2]=='St' and postag[3:5]=='It'))),
        'second_pick_int': (i==1 and postag[3:5]=='It'),
        'first_pick_int': (i==0 and postag[0:2]=='It'),
        'first_pick_st': (i==0 and postag[0:2]=='St'),
        'second_pick_st': (i==1 and postag[3:5]=='St'),
        'fourth_pick_ag': (i==3 and postag[9:11]=='Ag'),
        'fifth_pick_ag_or_it': (i==4 and ((postag[12:14]=='Ag') or (postag[12:14]=='It'))),    
    }

    return features


    
def sent2features(sent):
    return [word2features(sent, i) for i in range(len(sent))]

def sent2labels(sent):
    return [str(label) for token, postag, label in sent]

#def sent2tokens(sent):
    #return [token for token, postag, label in sent]

In [382]:
sent2features(train_sent[0])
#sent2labels(train_sent[0])
X_train = [sent2features(s) for s in train_sent]
y_train = [sent2labels(s) for s in train_sent]
X_test = [sent2features(s) for s in test_sent]
y_test = [sent2labels(s) for s in test_sent]
#X_train

In [383]:
from itertools import chain

import nltk
import sklearn
import scipy.stats
from sklearn.metrics import make_scorer
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import learning_curve, GridSearchCV
#from sklearn.grid_search import RandomizedSearchCV

import sklearn_crfsuite
from sklearn_crfsuite import scorers
from sklearn_crfsuite import metrics

In [388]:
crf = sklearn_crfsuite.CRF(
    algorithm='lbfgs',
    c1=0.1,
    c2=0.1,
    max_iterations=1000,
    all_possible_transitions=True
)
crf.fit(X_train, y_train)

CRF(algorithm='lbfgs', all_possible_transitions=True, c1=0.1, c2=0.1,
    keep_tempfiles=None, max_iterations=1000)

In [389]:
#labels = list(crf.classes_)
#labels.remove('O')
labels=['1', '-1']

In [390]:
y_pred = crf.predict(X_test)
metrics.flat_f1_score(y_test, y_pred,
                      average='weighted', labels=labels)


0.4898829332331945

In [391]:
y_pred

[['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['-1', '-1', '-1', '-1', '-1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['-1', '-1', '-1', '-1', '-1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['-1', '-1', '-1', '-1', '-1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['-1', '-1', '-1', '-1', '-1'],
 ['1', '1', '1', '1', '1'],
 ['-1', '-1', '-1', '-1', '-1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['-1', '-1', '-1', '-1', '-1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['1', '1', '1', '1', '1'],
 ['-1', '-1', '-1', '-1', '-1'],
 ['-1', '-1', '-1', '-1', '-1'],
 ['1', '1', '1', '1', '1'],
 ['-1', '-1', '-1', '-1', '-1'],
 ['

In [769]:
def tagging(match, hero_matrix):
    final_list=[]
    middle_value=""
    for element in range(2,7):
    #print(element)
        middle_tag = ""
        hero_entry = 0
        index_value = 0
        #print(match[element])
        #element = str(match[element])
        length = len(match[element])
        temp_list = hero_matrix[int(match[element][2:])-1]
        if temp_list[1]==1:
            middle_tag = "St"
        elif temp_list[2]==1:
            middle_tag = "Ag"
        elif temp_list[3]==1:
            middle_tag = "It"
        if element==6:
            index_value = 1000 
        else:
            index_value = match[element+1][2:]
        hero_entry = match[element][2:]
        middle_value +=  middle_tag + "/"
        final_list.append((hero_entry, middle_value, index_value))
             
    return final_list
        #temp_list = []
    '''
             if(length>=3 and length<=5):
            temp_list = hero_matrix[int(match[element][2:])-1]
            if temp_list[1]==1:
                middle_tag = "St"
            elif temp_list[2]==1:
                middle_tag = "Ag"
            elif temp_list[3]==1:
                middle_tag = "It"
            if element==4:
                index_value = 1000 
            else:
                index_value = match[element+1][2:]
            hero_entry = match[element][2:]
            middle_value +=  middle_tag + "/"
            final_list.append((hero_entry, middle_value, index_value))
             
    return final_list
        '''
        

dataset = []
for i in range(len(matrix1)):
    dataset.append(tagging(matrix1[i], matrix2))
len(dataset)
#train_sent = dataset[0:200000]
train_sent = dataset[0:18000]
test_sent = dataset[18000:20000]
#test_sent = dataset[200000:233735]
dataset
    #hero_info[int(token[2:])-1]

[[('28', 'St/', '29'),
  ('29', 'St/St/', '11'),
  ('11', 'St/St/Ag/', '75'),
  ('75', 'St/St/Ag/It/', '94'),
  ('94', 'St/St/Ag/It/Ag/', 1000)],
 [('74', 'It/', '35'),
  ('35', 'It/Ag/', '5'),
  ('5', 'It/Ag/It/', '70'),
  ('70', 'It/Ag/It/Ag/', '62'),
  ('62', 'It/Ag/It/Ag/Ag/', 1000)],
 [('42', 'St/', '26'),
  ('26', 'St/It/', '32'),
  ('32', 'St/It/Ag/', '97'),
  ('97', 'St/It/Ag/St/', '104'),
  ('104', 'St/It/Ag/St/St/', 1000)],
 [('30', 'It/', '70'),
  ('70', 'It/Ag/', '26'),
  ('26', 'It/Ag/It/', '81'),
  ('81', 'It/Ag/It/St/', '36'),
  ('36', 'It/Ag/It/St/It/', 1000)],
 [('26', 'It/', '4'),
  ('4', 'It/Ag/', '37'),
  ('37', 'It/Ag/It/', '34'),
  ('34', 'It/Ag/It/It/', '32'),
  ('32', 'It/Ag/It/It/Ag/', 1000)],
 [('32', 'Ag/', '54'),
  ('54', 'Ag/St/', '4'),
  ('4', 'Ag/St/Ag/', '71'),
  ('71', 'Ag/St/Ag/St/', '22'),
  ('22', 'Ag/St/Ag/St/It/', 1000)],
 [('11', 'Ag/', '1'),
  ('1', 'Ag/Ag/', '102'),
  ('102', 'Ag/Ag/St/', '57'),
  ('57', 'Ag/Ag/St/It/', '51'),
  ('51', 'Ag/Ag/St

In [799]:
def word2features(sent, i):
    word = sent[i][0]
    postag = sent[i][1]
    #print(word)
    #print("feature",sent,word, postag, i)
    #print(postag[0:2])
    features = {
        'bias': 1.0,
        'first_2_heros_int': (i==1 and postag[0:2]=='It' and postag[3:5]=='It'),
        'first_2_heros_st': (i==1 and postag[0:2]=='It' and postag[3:5]=='St'),
        'first_2_heros_ag': (i==1 and postag[0:2]=='It' and postag[3:5]=='Ag'),
        'alternate_condition_itst': (i==1 and ((postag[0:2]=='It' and postag[3:5]=='St')or(postag[0:2]=='St' and postag[3:5]=='It'))),
        'alternate_condition_stag': (i==1 and ((postag[0:2]=='St' and postag[3:5]=='Ag')or(postag[0:2]=='Ag' and postag[3:5]=='St'))),
        'alternate_condition_itag': (i==1 and ((postag[0:2]=='It' and postag[3:5]=='Ag')or(postag[0:2]=='Ag' and postag[3:5]=='It'))),
        'third_hero_st': (i==2 and postag[6:8]=='St'),
        'third_hero_it': (i==2 and postag[6:8]=='It'),
        'third_hero_ag': (i==2 and postag[6:8]=='Ag'),
        'second_pick_int': (i==1 and postag[3:5]=='It'),
        'second_pick_ag': (i==1 and postag[3:5]=='Ag'),
        'second_pick_st': (i==1 and postag[3:5]=='St'),
        'first_pick_int': (i==0 and postag[0:2]=='It'),
        'first_pick_st': (i==0 and postag[0:2]=='St'),
        'first_pick_ag': (i==0 and postag[0:2]=='Ag'),
        'fourth_pick_ag': (i==3 and postag[9:11]=='Ag'),
        'fourth_pick_it': (i==3 and postag[9:11]=='It'),
        'fourth_pick_st': (i==3 and postag[9:11]=='St'),
        'fifth_pick_ag_or_it': (i==4 and ((postag[12:14]=='Ag') or (postag[12:14]=='It'))),  
        'fifth_pick_ag': (i==4 and ((postag[12:14]=='Ag'))), 
        'fifth_pick_it': (i==4 and ((postag[12:14]=='It'))), 
        'fifth_pick_st': (i==4 and ((postag[12:14]=='St'))),   
    }   

   

    return features


    
def sent2features(sent):
    return [word2features(sent, i) for i in range(len(sent))]

def sent2labels(sent):
    return [str(label) for token, postag, label in sent]

In [800]:
sent2features(train_sent[0])
#sent2labels(train_sent[0])
X_train = [sent2features(s) for s in train_sent]
y_train = [sent2labels(s) for s in train_sent]
X_test = [sent2features(s) for s in test_sent]
y_test = [sent2labels(s) for s in test_sent]
len(X_train)

18000

In [801]:
crf = sklearn_crfsuite.CRF(
    #algorithm='lbfgs',
    algorithm='l2sgd',
    #c1=0.1,
    c2=1,
    max_iterations=1000,
    #all_possible_states = True,
    #period=2,
    all_possible_transitions=True
)
crf.fit(X_train, y_train)

CRF(algorithm='l2sgd', all_possible_transitions=True, c2=1, keep_tempfiles=None,
    max_iterations=1000)

In [802]:
my_labels=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56','57', '58', '59', '60','61', '62', '63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '110', '111', '112', '113'  ]

In [803]:
y_pred = crf.predict(X_test)
metrics.flat_f1_score(y_test, y_pred,
                      average='weighted', labels=labels)
sklearn_crfsuite.metrics.flat_accuracy_score(y_test, y_pred)

0.2303

In [807]:
#y_test
my_ytest = np.array(y_test)
#my_ytest_finalhero = my_ytest[:,0]
#my_ytest_finalhero = my_ytest[:,1]
my_ytest_finalhero = my_ytest[:,2]
#my_ytest_finalhero = my_ytest[:,3]
#my_ytest_finalhero = my_ytest[:,4]
#my_ytest_finalhero
#my_ypred = np.array(y_pred)
#my_ypred_finalhero = my_ypred[:,0]
#my_ypred_finalhero = my_ypred[:,1]
my_ypred_finalhero = my_ypred[:,2]
#my_ypred_finalhero = my_ypred[:,3]
#my_ypred_finalhero = my_ypred[:,4]
#my_ypred_finalhero
totals = my_ytest.shape[0]
#totals
num_correct = sum(p == t for p, t in zip(my_ypred_finalhero, my_ytest_finalhero))
#num_correct
total = (num_correct/totals)*100
total
print(my_ypred)
print("---------")
print(my_ytest)
print(total)
#y_pred

[['50' '67' '22' '67' '1000']
 ['7' '19' '91' '19' '1000']
 ['91' '19' '91' '19' '1000']
 ...
 ['7' '19' '91' '19' '1000']
 ['7' '19' '91' '19' '1000']
 ['7' '19' '91' '19' '1000']]
---------
[['37' '55' '19' '95' '1000']
 ['73' '37' '29' '5' '1000']
 ['41' '5' '74' '42' '1000']
 ...
 ['43' '100' '99' '14' '1000']
 ['64' '39' '29' '42' '1000']
 ['71' '112' '106' '48' '1000']]
1.0999999999999999
