In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
df = pd.read_csv("dataset_without_duplicates_Bans analysis.csv")

In [4]:
matrix1 =np.array(df.loc[:,['match_id','1hero_id','2hero_id','3hero_id','4hero_id']])
matrix1.shape

(461040, 5)

In [5]:
matrix1

array([[1928898739,         73,         69,         71,          7],
       [1928932285,         69,        102,         32,         61],
       [1928903165,         85,         68,         75,          2],
       ...,
       [1829187140,         44,         29,         12,         17],
       [1829220503,          1,         57,         50,         85],
       [1829227757,         71,        100,          7,         85]],
      dtype=int64)

In [6]:
df1 = pd.read_csv("hero_names.csv")
df1.head()

name  hero_id  localized_name  Strength  Agility  \
0        npc_dota_hero_antimage        1       Anti-Mage         0        1   
1             npc_dota_hero_axe        2             Axe         1        0   
2            npc_dota_hero_bane        3            Bane         0        0   
3     npc_dota_hero_bloodseeker        4     Bloodseeker         0        1   
4  npc_dota_hero_crystal_maiden        5  Crystal Maiden         0        0   

   Intelligence  
0             0  
1             0  
2             1  
3             0  
4             1

In [7]:
matrix2 =np.array(df1.loc[:,['hero_id', 'Strength','Agility','Intelligence']])

In [8]:
matrix2

array([[  1,   0,   1,   0],
       [  2,   1,   0,   0],
       [  3,   0,   0,   1],
       [  4,   0,   1,   0],
       [  5,   0,   0,   1],
       [  6,   0,   1,   0],
       [  7,   1,   0,   0],
       [  8,   0,   1,   0],
       [  9,   0,   1,   0],
       [ 10,   0,   1,   0],
       [ 11,   0,   1,   0],
       [ 12,   0,   1,   0],
       [ 13,   0,   0,   1],
       [ 14,   1,   0,   0],
       [ 15,   0,   1,   0],
       [ 16,   1,   0,   0],
       [ 17,   0,   0,   1],
       [ 18,   1,   0,   0],
       [ 19,   1,   0,   0],
       [ 20,   0,   1,   1],
       [ 21,   0,   0,   1],
       [ 22,   0,   0,   1],
       [ 23,   1,   0,   0],
       [ 24,   1,   1,   1],
       [ 25,   0,   0,   1],
       [ 26,   0,   0,   1],
       [ 27,   0,   0,   1],
       [ 28,   1,   0,   0],
       [ 29,   1,   0,   0],
       [ 30,   0,   0,   1],
       [ 31,   0,   0,   1],
       [ 32,   0,   1,   0],
       [ 33,   0,   0,   1],
       [ 34,   0,   0,   1],
       [ 35,  

In [9]:
from itertools import chain

import sklearn_crfsuite
from sklearn_crfsuite import scorers
from sklearn_crfsuite import metrics

import nltk
import sklearn
import scipy.stats
from sklearn.metrics import make_scorer
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import learning_curve, GridSearchCV

In [10]:
matrix1

array([[1928898739,         73,         69,         71,          7],
       [1928932285,         69,        102,         32,         61],
       [1928903165,         85,         68,         75,          2],
       ...,
       [1829187140,         44,         29,         12,         17],
       [1829220503,          1,         57,         50,         85],
       [1829227757,         71,        100,          7,         85]],
      dtype=int64)

In [19]:
my_input = matrix1[:,1:4]

In [20]:
my_input

array([[ 73,  69,  71],
       [ 69, 102,  32],
       [ 85,  68,  75],
       ...,
       [ 44,  29,  12],
       [  1,  57,  50],
       [ 71, 100,   7]], dtype=int64)

In [15]:
my_input.shape

(461040, 3)

In [32]:
my_output = matrix1[:,4]

In [33]:
my_output

array([ 7, 61,  2, ..., 17, 85, 85], dtype=int64)

In [56]:
train_x = my_input[:2000,:]
train_y = my_output[:2000]
test_x = my_input[2000:3000,:]
test_y = my_output[2000:3000]
test_x.shape

(1000, 3)

In [67]:
n_steps = 3
n_features = 1
train_x_to_conv = train_x.reshape((train_x.shape[0], train_x.shape[1], n_features))
print(train_x_to_conv.shape)
# define model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, n_features)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(train_x_to_conv, train_y, epochs=1000, verbose=0)
# demonstrate prediction
#x_input = array([70, 80, 90])
x_input = test_x
x_input = x_input.reshape((x_input.shape[0], n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

(2000, 3, 1)
[[64.42445   ]
 [37.546402  ]
 [55.433582  ]
 [68.89437   ]
 [51.905186  ]
 [54.443153  ]
 [60.003654  ]
 [58.39831   ]
 [62.064316  ]
 [48.37105   ]
 [61.32396   ]
 [52.198105  ]
 [55.101524  ]
 [36.90961   ]
 [58.467766  ]
 [52.719036  ]
 [59.90515   ]
 [51.68533   ]
 [50.76931   ]
 [58.4153    ]
 [51.572254  ]
 [47.329636  ]
 [61.310272  ]
 [56.912796  ]
 [52.974247  ]
 [61.957005  ]
 [45.390312  ]
 [51.01916   ]
 [63.526497  ]
 [68.528076  ]
 [29.5014    ]
 [69.10297   ]
 [52.295357  ]
 [61.32144   ]
 [47.973206  ]
 [72.546234  ]
 [51.460316  ]
 [59.748287  ]
 [63.892273  ]
 [61.40924   ]
 [55.158756  ]
 [40.98247   ]
 [54.33143   ]
 [68.89437   ]
 [52.149033  ]
 [ 0.18677819]
 [55.971157  ]
 [52.801743  ]
 [31.15482   ]
 [47.35487   ]
 [51.311035  ]
 [59.748287  ]
 [59.776665  ]
 [36.17987   ]
 [68.89437   ]
 [48.911945  ]
 [48.972725  ]
 [55.11428   ]
 [51.476334  ]
 [37.742577  ]
 [69.21525   ]
 [50.3584    ]
 [50.121628  ]
 [54.29345   ]
 [39.00599   ]
 [36.989777 

In [62]:
print(test_y)

[ 36  12  75 100  22  75  17  50  39  70  25  53  75  69  75   4 106 112
  99  28  86  99  74  61  39  11  40  32  69  91  75  67  67   7  30  73
  69  39  85  73  39  12  17 100  85  39  75  11  69  32 100  11  50  37
  60  85  29  28  69  46  12  82  16  75  41  72  14  75 100   1  28  21
  69  71 112   7  44  32  27  61  43   1  85  50  53  57  30  70  32  69
  69  28 100 100  63  99  57  75  12  75 112  42  73  85  30 100  57  99
 112  41  17  74  30  59  50  28  57  61  50  93   7  11 112  44  75  37
  81   7  50  28  73  75  69  42  69  32  12  32  59   1  30  73  30  73
  33  67  44  91  69  85  72  42  42  93  30  29  12  44  99  69  85  12
  21  68  12  30  60  85 100  12  69  57   1  74  85  32  57  69  75  46
  15  85   2  75  28  33  57  73  55  97  17  69  39 100  33  57  75  47
  75  12  41  85  69 112  21  73  69  42  34  59  95  39  30  19  69 104
  64 112  21  28  32  39  75  85  46  85  50 100  85  75  44  57  14  59
  12  85 100  17  17  75  85   8  69 100   7 100  6

In [26]:
#Credits : https://machinelearningmastery.com/how-to-develop-convolutional-neural-network-models-for-time-series-forecasting/
#!pip install tensorflow
#!pip install keras
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D

In [27]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)
 
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(n_steps, n_features)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(50, activation='relu'))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=1000, verbose=0)
# demonstrate prediction
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[101.35922]]


In [55]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)
 
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
print("X is: ", X)
print("Y is : ",y)
print("Y shape is : ",y.shape)
print("X shape 0 is: ", X.shape[0])
print("X shape 1 is: ", X.shape[1])
print("X shape is:", X.shape)
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print("X shape is:", X.shape)


X is:  [[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]
Y is :  [40 50 60 70 80 90]
Y shape is :  (6,)
X shape 0 is:  6
X shape 1 is:  3
X shape is: (6, 3)
X shape is: (6, 3, 1)
